PIDs:
  X:
    kp: 40.0
    kd: 20.0
    ki: 2.0
    minOutput: -15.0
    maxOutput: 15.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    kp: -40.0
    kd: -20.0
    ki: -2.0
    minOutput: -15.0
    maxOutput: 15.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp: 10000.0
    kd: 8000.0
    ki: 4000.0
    minOutput: 10000.0
    maxOutput: 60000.0
    integratorMin: -20
    integratorMax: 20
  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: -0.0
    integratorMax: 0.0
