PIDs:
  X:
    kp: 40.0
    kd: 20.0
    ki: 2.0
    minOutput: -7.0
    maxOutput: 7.0
    integratorMin: -1.0
    integratorMax: 1.0
  Y:
    kp: -40.0
    kd: -20.0
    ki: -2.0
    minOutput: -7.0
    maxOutput: 7.0
    integratorMin: -1.0
    integratorMax: 1.0
  Z:
    kp: 10000.0
    kd: 8000.0
    ki: 4000.0
    minOutput: 10000.0
    maxOutput: 60000.0
    integratorMin: 10
    integratorMax: 13
  Yaw:
    kp: -70.0
    kd: -5.0
    ki: 0.0
    minOutput: -120.0
    maxOutput: 120.0
    integratorMin: -0.0
    integratorMax: 0.0
